fisEndPoint = "ws://127.0.0.1:9944" 
keystorePath = "/Users/tpkeeper/gowork/stafi/fee-station/keys" 
logFilePath = "" 
payerAccount = "34PAx5KPyne2r8vHhBMaesFo1JCG57cnC5qNwSYWmgNmtaWP" 
swapMaxLimit = "150000000000000" #decimals 12
taskTicker = 10 # seconds

[db]
host = "127.0.0.1" # mysql host ip
name = "station" # the database this server used
port = "3306" 
pwd = "123456" # mysql password
user = "root" # mysql username
