fisTypesPath = "" 
keystorePath = "" 
logFilePath = "" 
swapMaxLimit = "15000000000000" #decimals 12
taskTicker = 10 # seconds

[db]
host = "127.0.0.1" # mysql host ip
name = "station" # the database this server used
port = "3306" 
pwd = "123456" # mysql password
user = "root" # mysql username
