basePath: /feeStation/api
definitions:
  station_handlers.PoolInfo:
    properties:
      poolAddress:
        description: base58 or hex
        type: string
      swapRate:
        description: decimals 6
        type: string
      symbol:
        type: string
    type: object
  station_handlers.ReqSwapInfo:
    properties:
      blockHash:
        description: hex
        type: string
      inAmount:
        description: decimal
        type: string
      minOutAmount:
        description: decimal
        type: string
      poolAddress:
        type: string
      pubkey:
        description: hex
        type: string
      signature:
        description: hex
        type: string
      stafiAddress:
        description: hex
        type: string
      symbol:
        type: string
      txHash:
        description: hex
        type: string
    type: object
  station_handlers.RspPoolInfo:
    properties:
      poolInfoList:
        items:
          $ref: '#/definitions/station_handlers.PoolInfo'
        type: array
      swapLimit:
        description: decimals 12
        type: string
    type: object
  station_handlers.RspSwapInfo:
    properties:
      swapStatus:
        type: integer
    type: object
  utils.Rsp:
    properties:
      data:
        type: object
      message:
        type: string
      status:
        type: integer
    type: object
host: localhost:8083
info:
  contact:
    email: tpkeeper.me@gmail.com
    name: tk
  description: drop api document.
  title: drop API
  version: "1.0"
paths:
  /v1/station/poolInfo:
    get:
      description: get pool info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Rsp'
            - properties:
                data:
                  $ref: '#/definitions/station_handlers.RspPoolInfo'
              type: object
      summary: get pool info
      tags:
      - v1
  /v1/station/swapInfo:
    get:
      description: get swap info
      parameters:
      - description: token symbol
        in: query
        name: symbol
        required: true
        type: string
      - description: block hash hex string
        in: query
        name: blockHash
        required: true
        type: string
      - description: tx hash hex string
        in: query
        name: txHash
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.Rsp'
            - properties:
                data:
                  $ref: '#/definitions/station_handlers.RspSwapInfo'
              type: object
      summary: get swap info
      tags:
      - v1
    post:
      consumes:
      - application/json
      description: post swap info
      parameters:
      - description: user swap info
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/station_handlers.ReqSwapInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Rsp'
      summary: post swap info
      tags:
      - v1
swagger: "2.0"
